name: tsoftmax
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - numpy=1.17.4
  - scipy=1.3.2
  - scikit-learn=0.22.1
  - pandas=0.25.1
  - pytorch=1.3.1
  - pillow=6.1.0
  - torchvision=0.4.2
  - cudatoolkit=10.0
  - matplotlib=3.1.1
  - lmdb=0.9.23
  - python-lmdb
