name: tsoftmax2
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - pytorch=1.7.1
  - pillow=6.1.0
  - torchvision
  - cudatoolkit=11
  - matplotlib
  - lmdb
  - python-lmdb
